//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DonHang
    {
        public int Id { get; set; }
        public int IdDonHang { get; set; }
        public int IdSach { get; set; }
        public int IdTaiKhoan { get; set; }
        public decimal DonGiaBan { get; set; }
        public int SoLuongBan { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
