//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PhieuNhap
    {
        public int Id { get; set; }
        public int MaPhieuNhap { get; set; }
        public int MaSach { get; set; }
        public int SoLuongNhap { get; set; }
        public decimal DonGiaNhap { get; set; }
        public decimal DonGiaBan { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual PhieuNhapSach PhieuNhapSach { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
