//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapSach
    {
        public PhieuNhapSach()
        {
            this.CT_PhieuNhap = new HashSet<CT_PhieuNhap>();
        }
    
        public int Id { get; set; }
        public int MaNCC { get; set; }
        public Nullable<System.DateTime> NgayNhapSach { get; set; }
        public Nullable<decimal> TongTienNhap { get; set; }
    
        public virtual ICollection<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
