-- PostgreSQL script for BookStoreDB
-- Run this script while connected to the BookStoreDB database.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Create BookStoreDB separately in PostgreSQL.

-- Bảng Vai trò
CREATE TABLE "VaiTro"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenVaiTro" VARCHAR(255) UNIQUE NOT NULL CHECK (length("TenVaiTro") > 0)
);

-- Bảng Nhà xuất bản
CREATE TABLE "NhaXuatBan"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenNXB" VARCHAR(255) UNIQUE NOT NULL CHECK (length("TenNXB") > 0)
);

-- Bảng Tác giả
CREATE TABLE "TacGia"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenTG" VARCHAR(255) UNIQUE NOT NULL CHECK (length("TenTG") > 0)
);

-- Bảng Thể loại
CREATE TABLE "TheLoai"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenTL" VARCHAR(255) UNIQUE NOT NULL CHECK (length("TenTL") > 0)
);

-- Bảng Nhà cung cấp
CREATE TABLE "NhaCungCap"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenNCC" VARCHAR(255) UNIQUE NOT NULL CHECK (length("TenNCC") > 0)
);

-- Bảng Sách
CREATE TABLE "Sach"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TenSach" VARCHAR(255) UNIQUE NOT NULL CHECK (length("TenSach") > 0),
    "IdNXB" INT NOT NULL REFERENCES "NhaXuatBan"("Id") ON DELETE CASCADE,
    "NamXuatBan" INT NOT NULL CHECK ("NamXuatBan" >= 1000 AND "NamXuatBan" <= EXTRACT(YEAR FROM CURRENT_DATE)::INT)
);

-- Bảng Tài khoản
CREATE TABLE "TaiKhoan"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   
	"HoTen" VARCHAR(255) NOT NULL CHECK (length("HoTen") > 0),
    "SoDienThoai" VARCHAR(10) UNIQUE NOT NULL,
    "Email" VARCHAR(255) UNIQUE NOT NULL,
    "MatKhau" BYTEA NOT NULL,
	"NgayTaoTaiKhoan" DATE DEFAULT(CURRENT_DATE) CHECK ("NgayTaoTaiKhoan" <= CURRENT_DATE),
    "Luong" NUMERIC(10, 2) NULL CHECK ("Luong" IS NULL OR "Luong" > 0),
    "IdVaiTro" INT NOT NULL REFERENCES "VaiTro"("Id") ON DELETE CASCADE, 
	CONSTRAINT "CK_TaiKhoan_SoDienThoai" CHECK ("SoDienThoai" ~ '^[0-9]{10}$'),
    CONSTRAINT "CK_TaiKhoan_MatKhau" CHECK (octet_length("MatKhau") > 0),
    CONSTRAINT "CK_TaiKhoan_Email" CHECK ("Email" LIKE '%@%.%')
);

-- Bảng Khách hàng
CREATE TABLE "KhachHang"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "HoTenKH" VARCHAR(255) NOT NULL CHECK (length("HoTenKH") > 0),
    "Email" VARCHAR(255) NULL,
    "SoDienThoai" VARCHAR(10) NULL,
    "DiaChi" VARCHAR(255) NULL,
    CONSTRAINT "CK_KhachHang_Email" CHECK ("Email" LIKE '%@%.%'),
    CONSTRAINT "CK_KhachHang_SoDienThoai" CHECK ("SoDienThoai" ~ '^[0-9]{10}$')
);

-- Bảng trung gian Sách - Tác giả
CREATE TABLE "Sach_TacGia"
(
    "IdSach" INT NOT NULL REFERENCES "Sach"("Id") ON DELETE CASCADE,
    "IdTacGia" INT NOT NULL REFERENCES "TacGia"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("IdSach", "IdTacGia")
);

-- Bảng trung gian Sách - Thể loại
CREATE TABLE "Sach_TheLoai"
(
    "IdSach" INT NOT NULL REFERENCES "Sach"("Id") ON DELETE CASCADE,
    "IdTheLoai" INT NOT NULL REFERENCES "TheLoai"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("IdSach", "IdTheLoai")
);

-- Bảng trung gian Sách - Nhà cung cấp
CREATE TABLE "Sach_NhaCungCap"
(
    "IdSach" INT NOT NULL REFERENCES "Sach"("Id") ON DELETE CASCADE,
    "IdNhaCungCap" INT NOT NULL REFERENCES "NhaCungCap"("Id") ON DELETE CASCADE,
    PRIMARY KEY ("IdSach", "IdNhaCungCap")
);

-- Bảng Đơn hàng
CREATE TABLE "DonHang"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NgayMuaHang" TIMESTAMP DEFAULT(CURRENT_TIMESTAMP) CHECK ("NgayMuaHang" <= CURRENT_TIMESTAMP),
    "IdKhachHang" INT NOT NULL REFERENCES "KhachHang"("Id") ON DELETE CASCADE,
    "TongTienBan" NUMERIC(15, 2) NULL
);

-- Bảng Chi tiết đơn hàng
CREATE TABLE "CT_DonHang"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdDonHang" INT NOT NULL REFERENCES "DonHang"("Id") ON DELETE CASCADE,
    "IdSach" INT NOT NULL REFERENCES "Sach"("Id") ON DELETE CASCADE,
    "IdTaiKhoan" INT NOT NULL REFERENCES "TaiKhoan"("Id") ON DELETE CASCADE,
    "DonGiaBan" NUMERIC(15, 2) NOT NULL CHECK ("DonGiaBan" > 0),
    "SoLuongBan" INT NOT NULL CHECK ("SoLuongBan" > 0)
);

-- Bảng "Kho"
CREATE TABLE "Kho"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "IdSach" INT NOT NULL REFERENCES "Sach"("Id") ON DELETE CASCADE,
    "SoLuongTon" INT NOT NULL DEFAULT 0 CHECK ("SoLuongTon" >= 0),
    "DonGiaNhap" NUMERIC(15, 2) NULL,
    "DonGiaBan" NUMERIC(15, 2) NULL
);

-- Bảng Phiếu nhập sách
CREATE TABLE "PhieuNhapSach"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"MaNCC" INT NOT NULL REFERENCES "NhaCungCap"("Id") ON DELETE CASCADE,
    "NgayNhapSach" TIMESTAMP DEFAULT(CURRENT_TIMESTAMP) CHECK ("NgayNhapSach" <= CURRENT_TIMESTAMP),
    "TongTienNhap" NUMERIC(15, 2) NULL
);

-- Bảng Chi tiết phiếu nhập
CREATE TABLE "CT_PhieuNhap"
(
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MaPhieuNhap" INT NOT NULL REFERENCES "PhieuNhapSach"("Id") ON DELETE CASCADE,
    "MaSach" INT NOT NULL REFERENCES "Sach"("Id") ON DELETE CASCADE,
    "SoLuongNhap" INT NOT NULL CHECK ("SoLuongNhap" > 0),
    "DonGiaNhap" NUMERIC(15, 2) NOT NULL CHECK ("DonGiaNhap" >= 0),
    "DonGiaBan" NUMERIC(15, 2) NOT NULL CHECK ("DonGiaBan" >= 0),
    "ThanhTien" NUMERIC(17, 2)
        GENERATED ALWAYS AS ("SoLuongNhap" * "DonGiaNhap") STORED,
	CONSTRAINT "CHK_DonGiaNhap_DonGiaBan" CHECK ("DonGiaNhap" <= "DonGiaBan")
);



-- PostgreSQL trigger functions and triggers
CREATE OR REPLACE FUNCTION "fn_UpdateStock_AfterInsertOrder"()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "Kho"
    SET "SoLuongTon" = "SoLuongTon" - NEW."SoLuongBan"
    WHERE "IdSach" = NEW."IdSach";
    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_UpdateStock_AfterInsertOrder"
AFTER INSERT ON "CT_DonHang"
FOR EACH ROW EXECUTE FUNCTION "fn_UpdateStock_AfterInsertOrder"();

CREATE OR REPLACE FUNCTION "fn_UpdateStock_AfterInsertReceipt"()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "Kho"
    SET "SoLuongTon" = "SoLuongTon" + NEW."SoLuongNhap"
    WHERE "IdSach" = NEW."MaSach";
    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_UpdateStock_AfterInsertReceipt"
AFTER INSERT ON "CT_PhieuNhap"
FOR EACH ROW EXECUTE FUNCTION "fn_UpdateStock_AfterInsertReceipt"();

CREATE OR REPLACE FUNCTION "fn_UpdateTongTienBan"()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_id INTEGER;
BEGIN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD."IdDonHang" ELSE NEW."IdDonHang" END;
    UPDATE "DonHang" d
    SET "TongTienBan" = COALESCE((
        SELECT SUM(c."DonGiaBan" * c."SoLuongBan")
        FROM "CT_DonHang" c
        WHERE c."IdDonHang" = v_id
    ), 0)
    WHERE d."Id" = v_id;

    IF TG_OP = 'UPDATE' AND OLD."IdDonHang" <> NEW."IdDonHang" THEN
        UPDATE "DonHang" d
        SET "TongTienBan" = COALESCE((
            SELECT SUM(c."DonGiaBan" * c."SoLuongBan")
            FROM "CT_DonHang" c
            WHERE c."IdDonHang" = OLD."IdDonHang"
        ), 0)
        WHERE d."Id" = OLD."IdDonHang";
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER "trg_UpdateTongTienBan"
AFTER INSERT OR UPDATE OR DELETE ON "CT_DonHang"
FOR EACH ROW EXECUTE FUNCTION "fn_UpdateTongTienBan"();

CREATE OR REPLACE FUNCTION "fn_UpdateTongTienNhap"()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_id INTEGER;
BEGIN
    v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD."MaPhieuNhap" ELSE NEW."MaPhieuNhap" END;
    UPDATE "PhieuNhapSach" p
    SET "TongTienNhap" = COALESCE((
        SELECT SUM(c."SoLuongNhap" * c."DonGiaNhap")
        FROM "CT_PhieuNhap" c
        WHERE c."MaPhieuNhap" = v_id
    ), 0)
    WHERE p."Id" = v_id;

    IF TG_OP = 'UPDATE' AND OLD."MaPhieuNhap" <> NEW."MaPhieuNhap" THEN
        UPDATE "PhieuNhapSach" p
        SET "TongTienNhap" = COALESCE((
            SELECT SUM(c."SoLuongNhap" * c."DonGiaNhap")
            FROM "CT_PhieuNhap" c
            WHERE c."MaPhieuNhap" = OLD."MaPhieuNhap"
        ), 0)
        WHERE p."Id" = OLD."MaPhieuNhap";
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER "trg_UpdateTongTienNhap"
AFTER INSERT OR UPDATE OR DELETE ON "CT_PhieuNhap"
FOR EACH ROW EXECUTE FUNCTION "fn_UpdateTongTienNhap"();

CREATE OR REPLACE FUNCTION "fn_UpdateKhoFromCT_PhieuNhap"()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "Kho"
    SET "DonGiaNhap" = NEW."DonGiaNhap",
        "DonGiaBan" = NEW."DonGiaBan"
    WHERE "IdSach" = NEW."MaSach";
    RETURN NEW;
END;
$$;

CREATE TRIGGER "trg_UpdateKhoFromCT_PhieuNhap"
AFTER INSERT OR UPDATE ON "CT_PhieuNhap"
FOR EACH ROW EXECUTE FUNCTION "fn_UpdateKhoFromCT_PhieuNhap"();

-- Thêm dữ liệu cho bảng "VaiTro" (Admin và Nhân viên)
INSERT INTO "VaiTro" ("TenVaiTro")
VALUES 
('Admin'), 
('Nhân viên');

-- Thêm dữ liệu cho bảng "NhaXuatBan"
INSERT INTO "NhaXuatBan" ("TenNXB")
VALUES 
('NXB Trẻ'),
('NXB Kim Đồng'),
('NXB Giáo Dục Việt Nam'),
('NXB Văn Học'),
('NXB Lao Động'),
('NXB Tổng Hợp TP.HCM'),
('NXB Hội Nhà Văn'),
('NXB Chính Trị Quốc Gia'),
('NXB Dân Trí'),
('NXB Phụ Nữ Việt Nam');

-- Thêm dữ liệu cho bảng "TacGia"
INSERT INTO "TacGia" ("TenTG")
VALUES 
('Nguyễn Nhật Ánh'),
('J.K. Rowling'),
('George Orwell'),
('Yuval Noah Harari'),
('Nguyễn Văn Dân'),
('Paulo Coelho'),
('Gabriel García Márquez'),
('Dan Brown'),
('Isaac Asimov'),
('Erich Fromm');

-- Thêm dữ liệu cho bảng "TheLoai"
INSERT INTO "TheLoai" ("TenTL")
VALUES 
('Văn học Việt Nam'),
('Văn học nước ngoài'),
('Khoa học viễn tưởng'),
('Tâm lý học'),
('Kinh tế học'),
('Giáo dục'),
('Thể thao'),
('Kỹ năng sống'),
('Lịch sử'),
('Tôn giáo');

-- Thêm dữ liệu cho bảng "NhaCungCap"
INSERT INTO "NhaCungCap" ("TenNCC")
VALUES 
('Công ty Fahasa'),
('Công ty Phương Nam'),
('Công ty Văn Hóa Sài Gòn'),
('Công ty Sách Alpha'),
('Công ty Sách Minh Long'),
('Công ty Sách Đông A'),
('Công ty Sách Nhã Nam'),
('Công ty Sách Tân Việt'),
('Công ty Sách Huy Hoàng'),
('Công ty Sách Tri Thức');

-- Thêm dữ liệu cho bảng "TaiKhoan"
INSERT INTO "TaiKhoan" ("HoTen", "SoDienThoai", "Email", "MatKhau", "IdVaiTro")
VALUES
('Võ Thành Hoàng Phúc', '0123456789', 'phucphuc2004444@gmail.com', digest('Hoangphuc@123', 'sha256'), 1),
('Võ Thành Hoàng Phúc', '0987654321', 'phucphucvo2004444@gmail.com', digest('Hoangphuc@123', 'sha256'), 2);

-- Thêm dữ liệu cho bảng "Sach"
INSERT INTO "Sach" ("TenSach", "IdNXB", "NamXuatBan")
VALUES 
('Tôi thấy hoa vàng trên cỏ xanh', 1, 2010),
('Harry Potter và Hòn đá phù thủy', 2, 2001),
('1984', 4, 1949),
('Sapiens: Lược sử loài người', 6, 2014),
('Một đời thương thuyết', 3, 2017),
('Nhà giả kim', 7, 1988),
('Trăm năm cô đơn', 5, 1967),
('Mật mã Da Vinci', 8, 2003),
('Nền văn minh vũ trụ', 9, 1951),
('Tự do hay là chết', 10, 1941),
('Tiếng gọi nơi hoang dã', 2, 1903),
('Chạng vạng', 3, 2005),
('The Great Gatsby', 4, 1925),
('Trăm năm yêu thương', 5, 2000),
('Lược sử thời gian', 6, 1988),
('Hoàng tử bé', 7, 1943),
('Tội ác và hình phạt', 8, 1866),
('Cuốn theo chiều gió', 9, 1936),
('Chí Phèo', 1, 1941),
('Dế mèn phiêu lưu ký', 1, 1942),
('Bố già', 5, 1969),
('Thuật xử thế', 6, 1936),
('Nghệ thuật đàm phán', 10, 1991),
('Tâm lý học đám đông', 4, 1895),
('Phía Tây không có gì lạ', 8, 1929),
('Một thoáng ta rực rỡ ở nhân gian', 9, 2019),
('Cô gái đến từ hôm qua', 1, 1990),
('Hạt giống tâm hồn', 6, 1999),
('Làng', 1, 1948);

-- Thêm dữ liệu cho bảng "KhachHang"
INSERT INTO "KhachHang" ("HoTenKH", "Email", "SoDienThoai", "DiaChi")
VALUES 
('Trần Văn An', 'vana@example.com', '0901234567', '123 Đường Trần Hưng Đạo, Quận 1, TP.HCM'),
('Nguyễn Thị Hồng Nhung', 'nthn@example.com', '0902345678', '456 Đường Lý Thái Tổ, Quận 3, TP.HCM'),
('Lê Văn Chí', 'lvc@example.com', '0903456789', '789 Đường Lý Thường Kiệt, Quận 5, TP.HCM'),
('Phạm Thị Thùy Dương', 'ptd@example.com', '0904567890', '123 Đường Nguyễn Văn Linh, Quận 7, TP.HCM'),
('Hoàng Văn Thụ', 'hve@example.com', '0905678901', '456 Đường 3/2, Quận 10, TP.HCM'),
('Vũ Thị Cẩm', 'vtf@example.com', '0906789012', '789 Đường Xô Viết Nghệ Tĩnh, Quận Bình Thạnh, TP.HCM'),
('Đặng Văn Giàu', 'dvg@example.com', '0907890123', '123 Đường Lê Trọng Tấn, Quận Tân Bình, TP.HCM'),
('Bùi Thị Hồng', 'bth@example.com', '0908901234', '456 Đường An Thạnh, Quận Phú Nhuận, TP.HCM'),
('Đỗ Văn Kiệt', 'dvi@example.com', '0909012345', '789 Đường Phạm Văn Đồng, Quận Gò Vấp, TP.HCM'),
('Nguyễn Thị Thập', 'ntj@example.com', '0900123456', '123 Đường Võ Chí Công, Quận 2, TP.HCM');

INSERT INTO "Sach_TacGia" ("IdSach", "IdTacGia")
VALUES 
(1, 1), -- Nguyễn Nhật Ánh
(2, 2), -- J.K. Rowling
(3, 3), -- George Orwell
(4, 4), -- Yuval Noah Harari
(5, 5), -- Nguyễn Văn Dân
(6, 6), -- Paulo Coelho
(7, 7), -- Gabriel García Márquez
(8, 8), -- Dan Brown
(9, 9), -- Isaac Asimov
(10, 10), -- Erich Fromm
(11, 3),
(12, 2),
(13, 5),
(14, 7),
(15, 9),
(16, 6),
(17, 1),
(18, 5),
(19, 8),
(20, 1),
(21, 1),
(22, 7),
(23, 10),
(24, 10),
(25, 4),
(26, 4),
(27, 8),
(28, 1),
(29, 6);

-- Thêm dữ liệu cho bảng "Sach_TheLoai" (liên kết sách với thể loại)
INSERT INTO "Sach_TheLoai" ("IdSach", "IdTheLoai")
VALUES 
(1, 1), -- Văn học Việt Nam
(2, 2), -- Văn học nước ngoài
(3, 2), -- Văn học nước ngoài
(4, 9), -- Lịch sử
(5, 8), -- Kỹ năng sống
(6, 8), -- Kỹ năng sống
(7, 2), -- Văn học nước ngoài
(8, 3), -- Khoa học viễn tưởng
(9, 3), -- Khoa học viễn tưởng
(10, 4), -- Tâm lý học
(11, 2),
(12, 2),
(13, 2),
(14, 2),
(15, 3),
(16, 9),
(17, 2),
(18, 1),
(19, 3),
(20, 1),
(21, 1),
(22, 4),
(23, 8),
(24, 8),
(25, 4),
(26, 9),
(27, 2),
(28, 1),
(29, 6);

-- Thêm dữ liệu cho bảng "Sach_NhaCungCap" (liên kết sách với nhà cung cấp)
INSERT INTO "Sach_NhaCungCap" ("IdSach", "IdNhaCungCap")
VALUES 
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10),
(11, 1),
(12, 2),
(13, 3),
(14, 4),
(15, 5),
(16, 6),
(17, 7),
(18, 8),
(19, 9),
(20, 10),
(21, 1),
(22, 2),
(23, 3),
(24, 4),
(25, 5),
(26, 6),
(27, 7),
(28, 8),
(29, 9);

-- Thêm dữ liệu cho bảng "Kho"
INSERT INTO "Kho" ("IdSach", "SoLuongTon")
VALUES 
(1, 100),
(2, 150),
(3, 200),
(4, 280),
(5, 120),
(6, 600),
(7, 500),
(8, 700),
(9, 400),
(10, 300),
(11, 350),
(12, 450),
(13, 250),
(14, 400),
(15, 700),
(16, 390),
(17, 980),
(18, 500),
(19, 430),
(20, 110),
(21, 100),
(22, 520),
(23, 304),
(24, 256),
(25, 703),
(26, 801),
(27, 408),
(28, 954),
(29, 609);
-- Thêm dữ liệu cho bảng "PhieuNhapSach"
INSERT INTO "PhieuNhapSach" ("MaNCC")
VALUES 
(1),
(2);
-- Thêm dữ liệu cho bảng "CT_PhieuNhap" (Chi tiết phiếu nhập)
INSERT INTO "CT_PhieuNhap" ("MaPhieuNhap", "MaSach", "SoLuongNhap", "DonGiaNhap", "DonGiaBan")
VALUES 
(1, 1, 30, 50000, 70000),
(1, 2, 40, 60000, 90000),
(2, 3, 20, 70000, 100000),
(2, 4, 25, 85000, 120000);
-- Thêm dữ liệu cho bảng "DonHang"
INSERT INTO "DonHang" ("IdKhachHang")
VALUES 
(1),
(2);
-- Thêm dữ liệu cho bảng "CT_DonHang" (Chi tiết đơn hàng)
INSERT INTO "CT_DonHang" ("IdDonHang", "IdSach", "IdTaiKhoan", "DonGiaBan", "SoLuongBan")
VALUES 
(1, 1, 1, 70000, 20),
(1, 2, 1, 90000, 10),
(2, 3, 2, 100000, 10),
(2, 4, 2, 120000, 30);
